kind = "DojoContract"
class_hash = "0x59ea8b26bda74baffdf6acf119971fcc3a49770356b9cce99963765f04b0768"
original_class_hash = "0x59ea8b26bda74baffdf6acf119971fcc3a49770356b9cce99963765f04b0768"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/game_center-Actions-38eede8c.json"
reads = []
writes = []
init_calldata = []
tag = "game_center-Actions"
systems = [
    "register_game",
    "update_game",
    "register_achievement",
    "update_achievement",
]
manifest_name = "game_center-Actions-38eede8c"
