kind = "DojoContract"
class_hash = "0x4536555d649bee5c56a0c2a8e2a4ff21c9ab110f0e43099b003b0d09ed13876"
original_class_hash = "0x4536555d649bee5c56a0c2a8e2a4ff21c9ab110f0e43099b003b0d09ed13876"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/game_center-Actions-38eede8c.json"
reads = []
writes = []
init_calldata = []
tag = "game_center-Actions"
systems = [
    "register_game",
    "update_game",
    "register_achievement",
    "update_achievement",
]
manifest_name = "game_center-Actions-38eede8c"
