[package]
cairo-version = "=2.7.0"
name = "conquest"
version = "0.0.0"

[cairo]
sierra-replace-ids = true

[scripts]
dev = "sozo clean && sozo build --typescript && sozo migrate plan && sozo migrate apply"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.13" }
bushido = { path = "../../../packages/bushido" }

[[target.dojo]]
build-external-contracts = [
    "bushido::models::index::Game",
    "bushido::models::index::Achievement",
    "bushido::events::index::AchievementCreation",
    "bushido::events::index::AchievementCompletion",
]
