kind = "DojoContract"
class_hash = "0x35779008542ea257c91936a2e22cb091044a5bef889f881108f7eccba4ec8f"
original_class_hash = "0x35779008542ea257c91936a2e22cb091044a5bef889f881108f7eccba4ec8f"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/conquest-Actions-4c864b1c.json"
reads = []
writes = []
init_calldata = []
tag = "conquest-Actions"
systems = [
    "signup",
    "conquest",
    "verify",
]
manifest_name = "conquest-Actions-4c864b1c"
