[world]
kind = "WorldContract"
class_hash = "0x5c4271c8cd454ceb8049d2b0724c99d12c2ef8077fc6ad325b18978f614aab0"
original_class_hash = "0x5c4271c8cd454ceb8049d2b0724c99d12c2ef8077fc6ad325b18978f614aab0"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x50ee3003ba7bdb4d072b0165c1f0f8645cccc21091e35c1b5164fd4fbac5cc8"
transaction_hash = "0x467db1103837d043ff5011341f68a0aab0ed18e9867ab43a350d7078174e6dc"
block_number = 3
seed = "bushido"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x69f3787ad4703fc9206195d5d1b8daa07dd97423a84f779207b3c27d283135a"
class_hash = "0x4375af2547229402f56da5e2b3343ec847684785959bc6e5ccdf8be239c248c"
original_class_hash = "0x4375af2547229402f56da5e2b3343ec847684785959bc6e5ccdf8be239c248c"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/game_center-Actions-38eede8c.json"
reads = []
writes = [
    "game_center-Game",
    "game_center-Achievement",
]
init_calldata = []
tag = "game_center-Actions"
systems = [
    "register_game",
    "update_game",
    "register_achievement",
    "update_achievement",
]
manifest_name = "game_center-Actions-38eede8c"

[[models]]
kind = "DojoModel"
class_hash = "0x1063f6e20ee5acfa2fc12e68a712c47495ea7af53629e5c7183eac45dd91a42"
original_class_hash = "0x1063f6e20ee5acfa2fc12e68a712c47495ea7af53629e5c7183eac45dd91a42"
abi = "manifests/dev/deployment/abis/models/game_center-Achievement-2d85ca77.json"
tag = "game_center-Achievement"
qualified_path = "bushido::models::index::achievement"
manifest_name = "game_center-Achievement-2d85ca77"

[[models.members]]
name = "world_id"
type = "felt252"
key = true

[[models.members]]
name = "namespace"
type = "felt252"
key = true

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "points"
type = "u16"
key = false

[[models.members]]
name = "whitelisted"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7877078cee53c30cdfc20402194db687cef0a0e178517ea125632dd0b6f548"
original_class_hash = "0x7877078cee53c30cdfc20402194db687cef0a0e178517ea125632dd0b6f548"
abi = "manifests/dev/deployment/abis/models/game_center-Game-6a4ff15e.json"
tag = "game_center-Game"
qualified_path = "bushido::models::index::game"
manifest_name = "game_center-Game-6a4ff15e"

[[models.members]]
name = "world_id"
type = "felt252"
key = true

[[models.members]]
name = "namespace"
type = "felt252"
key = true

[[models.members]]
name = "total_points"
type = "u16"
key = false

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "description"
type = "ByteArray"
key = false

[[models.members]]
name = "whitelisted"
type = "bool"
key = false

[[models.members]]
name = "torii_url"
type = "ByteArray"
key = false

[[models.members]]
name = "image_uri"
type = "ByteArray"
key = false
