[package]
cairo-version = "=2.7.0"
name = "bushido"
version = "0.0.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply"

[lib]

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.13" }
