
// Generated by dojo-bindgen on Thu, 3 Oct 2024 15:56:43 +0000. Do not modify this file manually.
// Import the necessary types from the recs SDK
// generate again with `sozo build --typescript` 
import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export type ContractComponents = Awaited<ReturnType<typeof defineContractComponents>>;



// Type definition for `dojo::model::layout::Layout` enum
export type Layout = { type: 'Fixed'; value: RecsType.NumberArray; } | { type: 'Struct'; value: RecsType.StringArray; } | { type: 'Tuple'; value: RecsType.StringArray; } | { type: 'Array'; value: RecsType.StringArray; } | { type: 'ByteArray'; } | { type: 'Enum'; value: RecsType.StringArray; };

export const LayoutDefinition = {
    type: RecsType.String,
    value: RecsType.String
};
        
// Type definition for `game_center::models::index::Achievement` struct
export interface Achievement {
    world_id: BigInt;
    namespace: BigInt;
    id: BigInt;
    points: Number;
    whitelisted: Boolean;
    
}
export const AchievementDefinition = {
    world_id: RecsType.BigInt,
    namespace: RecsType.BigInt,
    id: RecsType.BigInt,
    points: RecsType.Number,
    whitelisted: RecsType.Boolean,
    
};

// Type definition for `core::byte_array::ByteArray` struct
export interface ByteArray {
    data: String[];
    pending_word: BigInt;
    pending_word_len: Number;
    
}
export const ByteArrayDefinition = {
    data: RecsType.StringArray,
    pending_word: RecsType.BigInt,
    pending_word_len: RecsType.Number,
    
};

// Type definition for `dojo::model::layout::FieldLayout` struct
export interface FieldLayout {
    selector: BigInt;
    layout: Layout;
    
}
export const FieldLayoutDefinition = {
    selector: RecsType.BigInt,
    layout: LayoutDefinition,
    
};


// Type definition for `game_center::models::index::Game` struct
export interface Game {
    world_id: BigInt;
    namespace: BigInt;
    total_points: Number;
    name: String;
    description: String;
    whitelisted: Boolean;
    torii_url: String;
    image_uri: String;
    
}
export const GameDefinition = {
    world_id: RecsType.BigInt,
    namespace: RecsType.BigInt,
    total_points: RecsType.Number,
    name: RecsType.String,
    description: RecsType.String,
    whitelisted: RecsType.Boolean,
    torii_url: RecsType.String,
    image_uri: RecsType.String,
    
};


export function defineContractComponents(world: World) {
    return {

        // Model definition for `game_center::models::index::Achievement` model
        Achievement: (() => {
            return defineComponent(
                world,
                {
                    world_id: RecsType.BigInt,
                    namespace: RecsType.BigInt,
                    id: RecsType.BigInt,
                    points: RecsType.Number,
                    whitelisted: RecsType.Boolean,
                },
                {
                    metadata: {
                        namespace: "game_center",
                        name: "Achievement",
                        types: ["felt252", "felt252", "felt252", "u16", "bool"],
                        customTypes: [],
                    },
                }
            );
        })(),

        // Model definition for `game_center::models::index::Game` model
        Game: (() => {
            return defineComponent(
                world,
                {
                    world_id: RecsType.BigInt,
                    namespace: RecsType.BigInt,
                    total_points: RecsType.Number,
                    name: RecsType.String,
                    description: RecsType.String,
                    whitelisted: RecsType.Boolean,
                    torii_url: RecsType.String,
                    image_uri: RecsType.String,
                },
                {
                    metadata: {
                        namespace: "game_center",
                        name: "Game",
                        types: ["felt252", "felt252", "u16", "bool"],
                        customTypes: ["ByteArray", "ByteArray", "ByteArray", "ByteArray"],
                    },
                }
            );
        })(),
    };
}
