kind = "DojoModel"
class_hash = "0x12268045d00d4044b8f0ab2b3a9a3363a7e54c5e50d5bea296c754ef812dca2"
original_class_hash = "0x12268045d00d4044b8f0ab2b3a9a3363a7e54c5e50d5bea296c754ef812dca2"
abi = "manifests/slot/base/abis/models/conquest-AchievementCompletion-1d044dbd.json"
tag = "conquest-AchievementCompletion"
qualified_path = "bushido::events::index::achievement_completion"
manifest_name = "conquest-AchievementCompletion-1d044dbd"

[[members]]
name = "world_id"
type = "felt252"
key = true

[[members]]
name = "namespace"
type = "felt252"
key = true

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "player_id"
type = "felt252"
key = true

[[members]]
name = "progress"
type = "u8"
key = false

[[members]]
name = "time"
type = "u64"
key = false
